services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-taskverse_db}
      POSTGRES_USER: ${DB_USER:-daniel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-@daniel09033}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-daniel} -d ${DB_NAME:-taskverse_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: taskverse.django.local
      SECRET_KEY: ${SECRET_KEY:-dev-insecure-secret-key}
      DB_NAME: ${DB_NAME:-taskverse_db}
      DB_USER: ${DB_USER:-daniel}
      DB_PASSWORD: ${DB_PASSWORD:-@daniel09033}
      DB_HOST: postgres
      DB_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      CREATE_SUPERUSER: "1"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: taskverse.django.local
      SECRET_KEY: ${SECRET_KEY:-dev-insecure-secret-key}
      DB_NAME: ${DB_NAME:-taskverse_db}
      DB_USER: ${DB_USER:-daniel}
      DB_PASSWORD: ${DB_PASSWORD:-@daniel09033}
      DB_HOST: postgres
      DB_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      SKIP_DJANGO_BOOTSTRAP: "1"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A taskverse worker --loglevel=info

  beat:
    build: .
    environment:
      DJANGO_SETTINGS_MODULE: taskverse.django.local
      SECRET_KEY: ${SECRET_KEY:-dev-insecure-secret-key}
      DB_NAME: ${DB_NAME:-taskverse_db}
      DB_USER: ${DB_USER:-daniel}
      DB_PASSWORD: ${DB_PASSWORD:-@daniel09033}
      DB_HOST: postgres
      DB_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      SKIP_DJANGO_BOOTSTRAP: "1"
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A taskverse beat --loglevel=info -S django_celery_beat.schedulers:DatabaseScheduler

  flower:
    build: .
    ports:
      - "5555:5555"
    environment:
      DJANGO_SETTINGS_MODULE: taskverse.django.local
      SECRET_KEY: ${SECRET_KEY:-dev-insecure-secret-key}
      DB_NAME: ${DB_NAME:-taskverse_db}
      DB_USER: ${DB_USER:-daniel}
      DB_PASSWORD: ${DB_PASSWORD:-@daniel09033}
      DB_HOST: postgres
      DB_PORT: "5432"
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_HOST: redis
      SKIP_DJANGO_BOOTSTRAP: "1"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A taskverse flower

volumes:
  postgres_data:
