version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: taskverse_db
      POSTGRES_USER: daniel
      POSTGRES_PASSWORD: '@daniel09033'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U daniel"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build: ..
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=taskverse.django.local
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: python manage.py runserver 0.0.0.0:8000

  worker:
    build: ..
    environment:
      - DJANGO_SETTINGS_MODULE=taskverse.django.local
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A taskverse worker --loglevel=info

  beat:
    build: ..
    environment:
      - DJANGO_SETTINGS_MODULE=taskverse.django.local
    volumes:
      - ../:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A taskverse beat --loglevel=info

  flower:
    build: ..
    ports:
      - "5555:5555"
    environment:
      - DJANGO_SETTINGS_MODULE=taskverse.django.local
    volumes:
      - ../:/app
    depends_on:
      redis:
        condition: service_healthy
    command: celery -A taskverse flower --port=5555

volumes:
  postgres_data:
